
import javax.swing.border.TitledBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class CopyPanel extends javax.swing.JPanel {

    public static CopyPanel pan = null;
    
    /**
     * Creates new form CopyPanel
     * @param from
     * @param to
     */
    public CopyPanel(String from, String to) {
        initComponents();
        pan = this;
        ((TitledBorder)getBorder()).setTitle("Copying " + from + " to " + to + ".");
    }
    
    public void setCopying(String name){
        copyFileLabel.setText("Copying " + name + ".");
    }
    
    public void setSpeed(long speed){
        long data = speed;
        String type = "bytes";
        if(data / 1000 > 0){
            type = "KB";
            data /= 1000;
            if(data / 1000 > 0){
                type = "MB";
                data /= 1000;
                if(data / 1000 > 0){
                    type = "GB";
                    data /= 1000;
                    if(data / 1000 > 0){
                        type = "TB";
                        data /= 1000;
                    }
                }
            }
        }
        speedLabel.setText("Copying " + data + " " + type + " per second.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyFileLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Copying ... to ...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        setLayout(new java.awt.GridLayout(2, 0));

        copyFileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyFileLabel.setText("Copying ...");
        add(copyFileLabel);

        speedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        speedLabel.setText("Copying at 0 bytes");
        add(speedLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyFileLabel;
    private javax.swing.JLabel speedLabel;
    // End of variables declaration//GEN-END:variables
}
